### ISSUE TITLE
Phalcon benchmark doesn't enable HTML escaping

### ISSUE THREAD

**Issue by renannprado** [ndeet/pete#8]
In the go version, for example, the HTML escaping is enabled because it is using `html/template` package.
I might be wrong, but in the Phalcon benchmark I couldn't find the `autoescape` in the templates, which would have enabled the HTML escaping.

https://docs.phalconphp.com/en/3.0.0/reference/volt.html

**Comment by ndeet** [comment]
Hi,

I assume that you mean that Phalcon will then be a bit slower (in comparison to Go) because of autoescaping enabled? Not sure if slimphp and phoenix does that too. Beside that I'm not sure if the Go version is comparable anyway as it does not use any framework at all(?). So the other examples have to do some more bootstrapping I guess.

Also the benchmark was run with Phalcon 2.x (PHP 5.6.x) so maybe in the holidays I have time to do a Phalcon 3 benchmark using PHP 7.0.x (but can't promise).

**Comment by nicolasbernard** [comment]
Elixir do it already.

**Comment by renannprado** [comment]
@ndeet if you are not sure that others are doing this and **for sure** Phalcon version is not doing this, it's a good idea to change go benchmark to you use `text/template` instead.
Or, according to @Nikkau, we should change all benchmarks to do HTML escaping. 
Until you have all the benchmarks in the same page, it's invalid.

**Comment by nicolasbernard** [comment]
I can make a Golang version with a framework if you think it's a better comparison.

**Comment by ndeet** [comment]
@renannprado 
Ok, do you think the difference between autoescape results in a much better request per second ratio? Don't get me wrong, but if it is only a few percent difference the overall stats would not change that much and likely not change any of the rankings. If it is significant though, we should go for it.

@Nikkau 
If there exists any common/lightweight web framework for Go that would be awesome, as all other examples use some kind of framework and not only bare metal language speed.
